apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-deployment
    tier: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: contianer
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
