apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  # Using POD declaration embedded, it needs template
  template:
    metadata: 
      name: my-app
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  # Set the number of replicas
  replicas: 3
---
# kubectl create -f rc-definition.yaml
# kubectl get replicationcontroller
# kubectl get pods