apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  # modify replicas according to your case
  replicas: 3
  # Allow to consider other PODs name to inclde as part the cluster
  selector:
    matchLabels:
      type: front-end
  template:
    metadata: 
      name: my-app
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
---
# kubectl create -f replicaset-definition.yaml
# kubectl get replicaset
# kubectl get pods